### ISSUE TITLE
Not responding when click the "View" button

### ISSUE THREAD

**Issue by MingoLi** [yihuashub/PopcornMovie#2]
<img width="410" alt="Screen Shot 2019-05-06 at 11 33 47 AM" src="https://user-images.githubusercontent.com/28665314/57239945-eff39e80-6ff2-11e9-960b-cae8df8193db.png">

But works fine when clicking the left side (the cover image and title part)

**Comment by yihuashub** [comment]
the bug has been fixed, please update.
